server.port=8080

#jar or api
application.type=api


com.language.logging.level=DEBUG

language.detector=DEBUG

aws.accessKeyId=AKIATNVEVHRB2OSN7ACY
aws.secretAccessKey=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
aws.region=ap-south-1