server.port=8082

#jar or api
application.type=api


com.language.logging.level=DEBUG

language.detector=DEBUG

vocalKord.aws.accessKeyId=${vocalKord.aws.accessKeyId}
vocalKord.aws.secretAccessKey=${vocalKord.aws.secretAccessKey}