server.port=${SERVER_PORT}

#jar or api
application.type=api


com.language.logging.level=DEBUG

language.detector=DEBUG

AWS_S3_ACCESS_KEY=AKIATNVEVHRB2OSN7ACY
AWS_S3_SECRET_ACCESS_KEY=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